/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package grupo10_tp4_colegio;

import javax.swing.JOptionPane;

/**
 *
 * @author GRUPO 10
 * 
 * Altamirano Karina
 * Gianfranco Antonacci Matías
 * Bequis Marcos Ezequiel
 * Dave  Natalia
 * Quiroga Dorzan Alejo
 * Franzinni Tatiana
 */
public class VistaMaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaMaterias
     */
    public VistaMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelCodigoDeLaMateria = new javax.swing.JLabel();
        jLabelNombreDeLaMateria = new javax.swing.JLabel();
        jLabelAnioAlQuePertenece = new javax.swing.JLabel();
        txt_cod = new javax.swing.JTextField();
        txt_anio = new javax.swing.JTextField();
        txt_materia = new javax.swing.JTextField();
        btn_salir = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();

        setBorder(null);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Formulario de materias");

        jLabelCodigoDeLaMateria.setText("Codigo de la materia");

        jLabelNombreDeLaMateria.setText("Nombre de la materia");

        jLabelAnioAlQuePertenece.setText("Año al que pertenece");

        btn_salir.setText("Salir");
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_nuevo.setText("Nuevo");
        btn_nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_guardar)
                            .addGap(18, 18, 18)
                            .addComponent(btn_nuevo)
                            .addGap(41, 41, 41)
                            .addComponent(btn_salir))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNombreDeLaMateria)
                                .addGap(18, 18, 18)
                                .addComponent(txt_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelCodigoDeLaMateria)
                                .addGap(18, 18, 18)
                                .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAnioAlQuePertenece)
                        .addGap(21, 21, 21)
                        .addComponent(txt_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoDeLaMateria)
                    .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreDeLaMateria)
                    .addComponent(txt_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAnioAlQuePertenece)
                    .addComponent(txt_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salir)
                    .addComponent(btn_nuevo)
                    .addComponent(btn_guardar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
        txt_cod.setText("");
        txt_materia.setText("");
        txt_anio.setText("");
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        try {
            /* Validar campos vacíos, se usa ".trim().isEmpty()" 
            ya que trim detecta vacios reales, ejemplo:

            String t = "    ";  
            System.out.println(t.isEmpty()); // false

            String t = "    ";  
            System.out.println(t.trim().isEmpty()); // true */
            
            if (txt_cod.getText().trim().isEmpty() || txt_materia.getText().trim().isEmpty() || txt_anio.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(this,"Ningún campo puede quedar vacío.","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Parsear números (lanza exception si hay letras)
            int idMateria = Integer.parseInt(txt_cod.getText().trim());
            int anio = Integer.parseInt(txt_anio.getText().trim());
            String nombre = txt_materia.getText().trim();

            // Verificar que no se repita el codigo con el hashset
            boolean existe = false;
            for (Materia aux : Colegio.materia) {
                if (aux.getIdMateria() == idMateria) {
                    existe = true;
                    break;
                }
            }

            if (existe) {
                JOptionPane.showMessageDialog(this,"Ya existe una materia con ese código.","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Crear nueva materia y agregar al HashSet
            Materia m = new Materia(idMateria, nombre, anio);
            Colegio.materia.add(m);
            
            //Comprueba por consola cada vez que se agrega una materia por consola (NO DESMARCAR)
            /*
            System.out.println("\n----------------------------------------------");
            for(Materia aux : Colegio.materia){
                System.out.println("idMateria: " + aux.getIdMateria() + "\nnombre: " + aux.getNombre() + "\nanio: " + aux.getAnio());
                System.out.println("----------------------------------------------\n");
            }
            System.out.println("----------------------------------------------\n");
            */
            
            JOptionPane.showMessageDialog(this,"Materia guardada correctamente.");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El código y el año deben ser números enteros.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAnioAlQuePertenece;
    private javax.swing.JLabel jLabelCodigoDeLaMateria;
    private javax.swing.JLabel jLabelNombreDeLaMateria;
    private javax.swing.JTextField txt_anio;
    private javax.swing.JTextField txt_cod;
    private javax.swing.JTextField txt_materia;
    // End of variables declaration//GEN-END:variables
}
